version: "3.8"

services:
  parse-pdf-api:
      # NOTE: 目前 parse-pdf-api 的cpu/gpu模式要使用不同的docker image
      image: ${PARSE_PDF_API_IMAGE}
      container_name: mineru_server
      ports:
        - "8888:8000"
      volumes:
        - ~/.paddleocr:/root/.paddleocr:ro
        - ~/hf/PDF-Extract-Kit/models/:/opt/models:ro
        - ${PARSE_PDF_API_OUTPUT_DIR}:/root/output
      entrypoint: ['/usr/bin/dumb-init', '--']
      command: >
        bash -c '
        sed -i s/\"device-mode\".*/\"device-mode\":\"${CONVERTER_MODE}\",/g /root/magic-pdf.json && bash docker-entrypoint.sh
        '
      environment:
        # 取消代理，否則當host有掛代理的狀況，容器內的health check會失敗
        http_proxy: ""
        https_proxy: ""
        HTTP_PROXY: ""
        HTTPS_PROXY: ""
        BASE_DIR: /data/knowledges
        NVIDIA_VISIBLE_DEVICES: ${CONVERTER_CUDA_VISIBLE_DEVICES}
      restart: unless-stopped
      runtime: ${CONVERTER_RUNTIME}
